### ISSUE TITLE
About result visualization~~

### ISSUE THREAD

**Issue by kronaldo123** [XiaolongTang23/HPNet#13]
Hello, I have run the test.py with the argoverse forecasting dataset and have got an submission.h5 file. Can you offer the visualization code for me

Thanks a lot~

**Comment by XiaolongTang23** [comment]
Thank you for your interest in this work.  However, I don't have code to visualize the submission. h5 file.  I usually use a visualization function at the end of each step in validation/testing, rather than using the submission. h5 file.  Since my visualization code is very simple and not aesthetically pleasing, I didn't include it in this repository.  If you have any difficulties with visualization, please feel free to contact me via email at tangxiaolong22s@ict.ac.cn.
