### ISSUE TITLE
Detail for the Ensembled Model

### ISSUE THREAD

**Issue by LongLiveForFreedom** [XiaolongTang23/HPNet#24]
Hi! Thank you for your great work! And I have a question about the ensembled model that you mentioned in your paper. I did not find the code about the ensembling techniques and the model trained through this repo can just achieve performence of the single mode in your paper. Can you provide the code about this or make an explanation? Thank you!

**Comment by XiaolongTang23** [comment]
Thank you for your kind words and great question!

I didn't spend too much time focusing on ensembling because it's quite challenging to implement for real-time applications. For the ensembling, I used the same approach as QCNet, where I ensembled 10 models trained with different random seeds or slight variations in their architecture. You can refer to the supplementary materials of QCNet for more details on the ensembling technique.

I hope this helps! Feel free to reach out if you have any more questions.

**Comment by LongLiveForFreedom** [comment]
This help me a lot, thx!
