### ISSUE TITLE
Compare with QCNet

### ISSUE THREAD

**Issue by zhengyang-ponyai** [XiaolongTang23/HPNet#4]
Great work. I have two questions
1. QCNet shares similar accuracy on argoverse v1 dataset with this work, I wonder what's the difference your work with QCNet.
2. I can't see HPNet in Argoverse2 leader board. Can you show some results on Argoverse-v2 dataset?

**Comment by XiaolongTang23** [comment]
Thank you for bringing up these critical questions.   

Let's tackle the second question first.   We have tried to conduct experiments on the larger Argoverse2 and WOMD datasets.   However, due to HPNet's design to predict trajectories for multiple agents and multiple moments, it requires substantial memory.   Unfortunately, running HPNet on Argoverse2 and WOMD exceeded our available memory capacity (24GB).

As for your first question, QCNet indeed serves as an excellent baseline for its simplicity and outstanding performance.   The key distinction between our work and QCNet lies in our consideration of historical predictions, which enhances both the stability and accuracy of our predictions.   Moreover, HPNet is applicable for both marginal prediction and joint prediction while QCNet is for marginal only.   For a more detailed comparison, I encourage you to refer to our paper.

In terms of accuracy, our method actually outperforms QCNet on the Argoverse1 dataset when comparing single-model performances.   It's worth noting that because our method generates more stable results by leveraging historical predictions, the improvement from the ensemble was not as significant as QCNet.

**Comment by LongLiveForFreedom** [comment]
Hi, thank you for your great work! Can you tell me how long a complete training session takes on your 8 * 4090? If I just have 1 3090 with 24G GPU memory, can I train?

**Comment by XiaolongTang23** [comment]
> Hi, thank you for your great work! Can you tell me how long a complete training session takes on your 8 * 4090? If I just have 1 3090 with 24G GPU memory, can I train?

Hi!
On the Argoverse dataset, a complete training session using 8 * 4090 takes approximately 30 minutes per epoch. For a full training session of 64 epochs, it takes around 32 hours.

**Comment by LongLiveForFreedom** [comment]
Thank you for your reply！
