### ISSUE TITLE
Question about Argoverse dataset

### ISSUE THREAD

**Issue by kkk00714** [XiaolongTang23/HPNet#7]
Hello, could you please give me a personal contact information? I have some questions about Argoverse dataset processing to ask you, thank you very much!

**Comment by kkk00714** [comment]
@XiaolongTang23

**Comment by XiaolongTang23** [comment]
You can contact me via my email at tangxiaolong22s@ict.ac.cn, and I would be happy to assist you if I can. Alternatively, you are welcome to ask your questions here directly. Perhaps others in the community can also provide you with helpful insights.

**Comment by kkk00714** [comment]
Okay, here are my questions:

The CSV files in Argoverse often contain missing frames, for example jumping directly from frame 1 to frame 3. How do you fill these missing frames?
If I have 10 historical frames, that means I can only calculate speed for 9 frames (and acceleration for 8 frames). How do you fill in the speed and acceleration?
How can I obtain the local map for a specific case (i.e., a specific CSV file) in the dataset?

I know these are some simple questions, and I would be extremely grateful if you could answer them for me.

**Comment by kkk00714** [comment]
@XiaolongTang23

**Comment by XiaolongTang23** [comment]
1.    Missing Frames in CSV: Instead of attempting to fill these missing frames, I use a masking approach to denote the visibility of data in each frame.  The model then processes only the frames that are marked as visible.
2.    Calculating Speed and Acceleration: For the initial frames where speed and acceleration cannot be directly calculated due to insufficient data (e.g., the first two frames for acceleration), a common approach is to simply set these values to zero.       Alternatively, you could assume that the speed or acceleration remains constant from the available frames, using data from subsequent frames to estimate these initial values.  This is typically a reasonable approximation and generally does not significantly impact the performance of most models.
3.   Obtaining Local Maps: Argoverse provides utility functions, such as get_lane_ids_in_xy_bbox, which you can use to extract relevant map information for specific scenarios or CSV files.

I hope you find these insights helpful!
